import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import Navigation from "@/components/navigation/navigation";
import FooterComponent from "@/components/footer/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geist = Noto_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        {children}
        <Navigation />
        <FooterComponent />
      </body>
    </html>
  );
}
