// app/layout.tsx  (RootLayout)
import { Noto_Sans } from "next/font/google";
import Navigation from "@/components/navigation/navigation";
import FooterComponent from "@/components/footer/footer";
import { DrawerProvider } from "@/context/DrawerContext";
import "./globals.css";

const geist = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <DrawerProvider>
          <main className="ml-[60px]">
            {children}
            <Navigation />
          </main>
          <FooterComponent />
        </DrawerProvider>
      </body>
    </html>
  );
}
